import { z } from "zod";
import { eq } from "drizzle-orm";
import { writeFile, readFile } from "node:fs/promises";
import { join } from "node:path";
import { publicProcedure, router } from "../..";
import { localDb } from "main/lib/local-db";
import { atlasIntegrations, atlasProjects } from "@superset/local-db";
import { encrypt, decrypt } from "../auth/utils/crypto-storage";

const NEON_API = "https://console.neon.tech/api/v2";

async function getNeonApiKey(): Promise<string> {
	const envKey = process.env.NEON_API_KEY;
	if (envKey) return envKey;

	const [integration] = await localDb
		.select()
		.from(atlasIntegrations)
		.where(eq(atlasIntegrations.service, "neon"));
	if (!integration) throw new Error("Neon API key not configured");
	return decrypt(integration.encryptedToken);
}

async function neonFetch(path: string, options: RequestInit = {}) {
	const apiKey = await getNeonApiKey();
	const res = await fetch(`${NEON_API}${path}`, {
		...options,
		headers: {
			Authorization: `Bearer ${apiKey}`,
			"Content-Type": "application/json",
			...options.headers,
		},
	});
	if (!res.ok) {
		const body = await res.text();
		throw new Error(`Neon API error (${res.status}): ${body}`);
	}
	return res.json();
}

export const createAtlasNeonRouter = () =>
	router({
		saveToken: publicProcedure
			.input(z.object({ token: z.string().min(1) }))
			.mutation(async ({ input }) => {
				// Verify token by calling /projects
				try {
					const res = await fetch(`${NEON_API}/projects?limit=1`, {
						headers: { Authorization: `Bearer ${input.token}` },
					});
					if (!res.ok) throw new Error("Invalid token");
				} catch {
					throw new Error(
						"토큰 검증 실패: Neon에 연결할 수 없습니다",
					);
				}

				const encrypted = encrypt(input.token);

				await localDb
					.delete(atlasIntegrations)
					.where(eq(atlasIntegrations.service, "neon"));

				await localDb.insert(atlasIntegrations).values({
					service: "neon",
					encryptedToken: encrypted,
				});

				return { success: true };
			}),

		removeToken: publicProcedure.mutation(async () => {
			await localDb
				.delete(atlasIntegrations)
				.where(eq(atlasIntegrations.service, "neon"));
			return { success: true };
		}),

		getConnectionStatus: publicProcedure.query(async () => {
			if (process.env.NEON_API_KEY) return { connected: true };
			const [integration] = await localDb
				.select()
				.from(atlasIntegrations)
				.where(eq(atlasIntegrations.service, "neon"));
			return { connected: !!integration };
		}),

		listOrganizations: publicProcedure.query(async () => {
			const data = await neonFetch("/organizations");
			return (data.organizations ?? data ?? []) as Array<{
				id: string;
				name: string;
			}>;
		}),

		createProject: publicProcedure
			.input(
				z.object({
					name: z.string().min(1),
					orgId: z.string().optional(),
					atlasProjectId: z.string().min(1),
				}),
			)
			.mutation(async ({ input }) => {
				const projectPayload: Record<string, unknown> = {
					name: input.name,
				};
				if (input.orgId) {
					projectPayload.org_id = input.orgId;
				}

				const data = await neonFetch("/projects", {
					method: "POST",
					body: JSON.stringify({ project: projectPayload }),
				});

				const project = data.project;
				const connectionUri =
					data.connection_uris?.[0]?.connection_uri ?? "";

				await localDb
					.update(atlasProjects)
					.set({
						neonProjectId: project.id,
						neonConnectionString: connectionUri,
						updatedAt: Date.now(),
					})
					.where(eq(atlasProjects.id, input.atlasProjectId));

				return {
					id: project.id,
					name: project.name,
					connectionUri,
				};
			}),

		getConnectionString: publicProcedure
			.input(z.object({ projectId: z.string().min(1) }))
			.query(async ({ input }) => {
				const data = await neonFetch(
					`/projects/${input.projectId}/connection_uri`,
				);
				return { connectionUri: data.uri as string };
			}),

		writeEnvFile: publicProcedure
			.input(
				z.object({
					projectPath: z.string(),
					connectionUri: z.string(),
					neonProjectId: z.string(),
				}),
			)
			.mutation(async ({ input }) => {
				const envPath = join(input.projectPath, ".env");
				let existing = "";
				try {
					existing = await readFile(envPath, "utf-8");
				} catch {
					// File doesn't exist yet
				}

				const neonEnv = [
					`DATABASE_URL=${input.connectionUri}`,
					`NEON_PROJECT_ID=${input.neonProjectId}`,
				].join("\n");

				const newContent = existing
					? `${existing}\n\n# Neon (auto-generated by Composer)\n${neonEnv}\n`
					: `# Neon (auto-generated by Composer)\n${neonEnv}\n`;

				await writeFile(envPath, newContent, "utf-8");
				return { envPath };
			}),
	});
