export type {
	WorkspaceFsCreateDirectoryInput,
	WorkspaceFsCreateFileInput,
	WorkspaceFsDeletePathsInput,
	WorkspaceFsDirectoryQuery,
	WorkspaceFsLocation,
	WorkspaceFsMoveCopyInput,
	WorkspaceFsMutationService,
	WorkspaceFsQueryService,
	WorkspaceFsRenameInput,
	WorkspaceFsSearchFilesInput,
	WorkspaceFsSearchService,
	WorkspaceFsService,
	WorkspaceFsWatchInput,
	WorkspaceFsWatchService,
	WorkspaceFsWriteFileInput,
} from "../core/service";
