import { randomBytes } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

export async function writeEnvFile(
	projectDir: string,
	vars: Record<string, string | undefined>,
): Promise<{ envPath: string }> {
	const envPath = join(projectDir, ".env");

	let existing = "";
	try {
		existing = await readFile(envPath, "utf-8");
	} catch {
		// File doesn't exist yet
	}

	// Filter out undefined values
	const entries = Object.entries(vars).filter(
		(entry): entry is [string, string] => entry[1] !== undefined,
	);

	// Auto-generate BETTER_AUTH_SECRET if not provided
	const hasBetterAuthSecret = entries.some(
		([key]) => key === "BETTER_AUTH_SECRET",
	);
	if (!hasBetterAuthSecret) {
		entries.push(["BETTER_AUTH_SECRET", randomBytes(32).toString("base64")]);
	}

	const envLines = entries.map(([key, value]) => `${key}=${value}`);
	const envBlock = envLines.join("\n");

	const newContent = existing
		? `${existing}\n\n# Auto-generated by Superbuilder Composer\n${envBlock}\n`
		: `# Auto-generated by Superbuilder Composer\n${envBlock}\n`;

	await writeFile(envPath, newContent, "utf-8");

	return { envPath };
}
